Andres markets page
overlay-market/overlay-interface-v2 pull request #6
Opened 2024-10-15 13:26 UTC by AndresImach

2024-10-29 13:24 UTC, TomasCImach requested changes

2024-10-29 13:24 UTC, TomasCImach commented on src/components/Banner/OptionalLinkBanner/OptionalLinkBanner.tsx
rename file to index.tsx to comply with naming standards.

https://discord.com/channels/798007956239024148/1288946967728357501/1289250156482400267

2024-10-29 13:24 UTC, TomasCImach commented on src/components/Banner/PromotedBanner/PromotedBanner.tsx
rename file to index.tsx to comply with naming standards.

https://discord.com/channels/798007956239024148/1288946967728357501/1289250156482400267

2024-10-29 13:24 UTC, TomasCImach commented on src/components/MarketCards/MarketCards.tsx
rename file to index.tsx to comply with naming standards.

https://discord.com/channels/798007956239024148/1288946967728357501/1289250156482400267

2024-10-29 13:24 UTC, TomasCImach commented on package.json
> +    "lucide-react": "^0.451.0",
this dependency is not being used

2024-10-29 13:24 UTC, TomasCImach commented on package.json
> +    "react-swiper": "^0.1.5",
this dependency is not being used

2024-11-08 13:08 UTC, TomasCImach approved these changes

2024-11-08 17:37 UTC, Aliona-D commented on src/components/Banner/Banners_.ts
this file should be renamed to banners-styles.ts

2024-11-08 17:43 UTC, Aliona-D commented on src/components/Banner/Banners_.ts
> +export const StyledFlex = styled(Flex)`
In such cases I avoid creating custom components but apply these styles directly in Flex component
<Flex direction={'column} justify={'start} align={'start'} width={'100%'} >

2024-11-08 17:45 UTC, Aliona-D commented on src/components/MarketCards/MarketCards_.ts
this file should be renamed to market-cards-styles.ts

2024-11-08 17:48 UTC, Aliona-D commented on src/pages/Markets/MarketsFirstSection.tsx
> +    <Flex gap="3" style={{ marginLeft: "50px" }}>
here it can be simplified
<Flex gap="3" ml="50px">

2024-11-08 17:53 UTC, Aliona-D commented on src/pages/Markets/MarketsTable.tsx
> +export type TransformedMarketData = {
type TransformedMarketData should be exported from sdk.

2024-11-08 17:54 UTC, Aliona-D commented on src/pages/Markets/MarketsTable.tsx
> +        console.log("activeMarkets", activeMarkets);
should be removed

2024-11-08 17:54 UTC, Aliona-D commented on src/pages/Markets/MarketsTable.tsx
> +  console.log("marketsData", marketsData[1]);
should be removed

2024-11-08 17:57 UTC, Aliona-D commented on src/theme/index.ts
> +    grey8: "#252534",
grey8 = grey4, thus can be removed

2024-11-08 17:59 UTC, Aliona-D commented on src/theme/theme.ts
this file duplicates the previous one

2024-11-18 14:07 UTC, closed without merging